export const GET_NETFLIX_ORIGINALS = "GET_NETFLIX_ORIGINALS"
export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES"
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES"
export const GET_TOPRATED_MOVIES = "GET_TOPRATED_MOVIES"
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES"
export const GET_NEWRELEASES_MOVIES = "GET_NEWRELEASES_MOVIES"


export const SET_MOVIE_DETAIL = "SET_MOVIE_DETAIL"
export const GET_SEARCH_MOVIES = "GET_SEARCH_MOVIES"



